# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["core.py"]

doc_url = "https://hoftherose.github.io"

git_url = "https://github.com/hoftherose/MiniML/tree/master/"

def custom_doc_links(name): return None
