# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Categorize": "Clustering.ipynb",
         "cat": "Clustering.ipynb",
         "plot_iris": "Clustering.ipynb",
         "k": "Clustering.ipynb",
         "it": "Clustering.ipynb",
         "data": "Clustering.ipynb",
         "centers": "Clustering.ipynb",
         "dist": "Clustering.ipynb",
         "get_distances": "Clustering.ipynb",
         "calc_centers": "Clustering.ipynb",
         "np_results": "Clustering.ipynb",
         "results": "Clustering.ipynb",
         "c_flowers": "Clustering.ipynb",
         "one_hot": "Clustering.ipynb",
         "one_hot_show": "Clustering.ipynb",
         "c_plot_iris": "Clustering.ipynb",
         "c_calc_centers": "Clustering.ipynb",
         "update_u": "Clustering.ipynb",
         "distances": "Clustering.ipynb",
         "c_data": "Clustering.ipynb",
         "U": "Clustering.ipynb",
         "eps": "Clustering.ipynb"}

modules = ["clustering.py"]

doc_url = "https://hoftherose.github.io"

git_url = "https://github.com/hoftherose/MiniML/tree/master/"

def custom_doc_links(name): return None
