# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Categorize": "Clustering.ipynb",
         "cat": "Clustering.ipynb",
         "plot_iris": "Clustering.ipynb",
         "k": "Clustering.ipynb",
         "it": "Clustering.ipynb",
         "data": "Clustering.ipynb",
         "centers": "Clustering.ipynb",
         "c_plot_iris": "Clustering.ipynb"}

modules = ["core.py"]

doc_url = "https://hoftherose.github.io"

git_url = "https://github.com/hoftherose/MiniML/tree/master/"

def custom_doc_links(name): return None
